version: "3"

services:
  postgres:
    container_name: postgres
    image: postgres
    healthcheck:
      test: psql postgres --command "select 1" -U postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    networks:
      - pact_example

  pactbroker:
    container_name: pactbroker
    image: pactfoundation/pact-broker
    links:
      - postgres
    ports:
      - "9292:9292"
    environment:
      PACT_BROKER_BASIC_AUTH_USERNAME: pact_workshop
      PACT_BROKER_BASIC_AUTH_PASSWORD: pact_workshop
      PACT_BROKER_DATABASE_USERNAME: postgres
      PACT_BROKER_DATABASE_PASSWORD: password
      PACT_BROKER_DATABASE_HOST: postgres
      PACT_BROKER_DATABASE_NAME: postgres
      PACT_BROKER_WEBHOOK_SCHEME_WHITELIST: http
      PACT_BROKER_WEBHOOK_HOST_WHITELIST: jenkins host.docker.internal
    depends_on:
      - postgres
    networks:
      - pact_example

#  jenkins:
#    container_name: jenkins
#    image: jenkins/jenkins
#    ports:
#      - "8080:8080"
#    volumes:
#      - ~/Jenkins/jenkins_home:/var/jenkins_home
#    networks:
#      - pact_example

networks:
  pact_example:
